spring:
  datasource:
    url: jdbc:postgresql://localhost:2222/imagelite_db
    username: postgres
    password: Info@1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect